sonar.organization=venessa3105-hash
sonar.projectKey=venessa3105-hash_sample-vulnerable-app

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/venv/**,**/node_modules/**,**/.git/**,**/__pycache__/**

sonar.python.version=3.12
